<?xml version='1.0' encoding='UTF-8'?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Settings">
        <text>Touchify</text>
        <Action name="touchify_hotkey_1">
            <shortcut></shortcut>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
        </Action>
        <Action name="touchify_hotkey_2">
            <shortcut></shortcut>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
        </Action>
        <Action name="touchify_hotkey_3">
            <shortcut></shortcut>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
        </Action>
        <Action name="touchify_hotkey_4">
            <shortcut></shortcut>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
        </Action>
        <Action name="touchify_hotkey_5">
            <shortcut></shortcut>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
        </Action>
        <Action name="touchify_hotkey_6">
            <shortcut></shortcut>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
        </Action>
        <Action name="touchify_hotkey_7">
            <shortcut></shortcut>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
        </Action>
        <Action name="touchify_hotkey_8">
            <shortcut></shortcut>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
        </Action>
        <Action name="touchify_hotkey_9">
            <shortcut></shortcut>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
        </Action>
        <Action name="touchify_hotkey_10">
            <shortcut></shortcut>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
        </Action>
        <Action name="touchify_configure">
            <shortcut></shortcut>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
        </Action>
        <Action name="touchify_showToolbox">
            <icon></icon>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>shift+t</shortcut>
            <isCheckable>true</isCheckable>
            <statusTip></statusTip>
        </Action>
        <Action name="touchify_showToolshelf">
            <icon></icon>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>n</shortcut>
            <isCheckable>true</isCheckable>
            <statusTip></statusTip>
        </Action>
        <Action name="touchify_showToolshelfAlt">
            <icon></icon>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>true</isCheckable>
            <statusTip></statusTip>
        </Action>
        <Action name="touchify_showPopupPalette">
            <icon></icon>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
        <Action name="touchify_showPopupMenu">
            <icon></icon>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>            
        </Action>
    </Actions>
</ActionCollection>