
from krita import DockWidgetFactory, DockWidgetFactoryBase, Krita
from .variables import *
from .components.touchify.dockers.color_options.ColorOptionsDocker import ColorOptionsDocker
from .components.touchify.dockers.brush_options.BrushOptionsDocker import BrushOptionsDocker
from .components.touchify.dockers.toolshelf.ToolshelfDocker import TouchifyToolshelfDocker
from .components.touchify.dockers.reference_tabs.ReferenceTabsDocker import ReferenceTabsDocker

Krita.instance().addDockWidgetFactory(DockWidgetFactory(TOUCHIFY_ID_DOCKER_COLOROPTIONSDOCKER, DockWidgetFactoryBase.DockPosition.DockRight, ColorOptionsDocker))
Krita.instance().addDockWidgetFactory(DockWidgetFactory(TOUCHIFY_ID_DOCKER_BRUSHOPTIONSDOCKER, DockWidgetFactoryBase.DockPosition.DockRight, BrushOptionsDocker))
Krita.instance().addDockWidgetFactory(DockWidgetFactory(TOUCHIFY_ID_DOCKER_TOOLSHELFDOCKER, DockWidgetFactoryBase.DockPosition.DockRight, TouchifyToolshelfDocker))
Krita.instance().addDockWidgetFactory(DockWidgetFactory(TOUCHIFY_ID_DOCKER_REFERENCETABSDOCKER, DockWidgetFactoryBase.DockPosition.DockRight, ReferenceTabsDocker))