TOUCHIFY_ID_ACTIONS_ROOT="Touchify"
TOUCHIFY_ID_ACTIONS_HOTKEY="hotkey"
TOUCHIFY_ID_ACTIONS_WORKSPACE="workspace"
TOUCHIFY_ID_ACTIONS_DOCKER="docker"
TOUCHIFY_ID_ACTIONS_POPUP="popup"
TOUCHIFY_ID_ACTIONS_DOCKER_GROUP="docker_group"

TOUCHIFY_AID_ACTIONS_WORKSPACE="workspace"
TOUCHIFY_AID_ACTIONS_DOCKER="docker"
TOUCHIFY_AID_ACTIONS_POPUP="popup"
TOUCHIFY_AID_ACTIONS_DOCKER_GROUP="group"

TOUCHIFY_TOOLBOX_DOCKER_ID='TouchifyToolbox'