# Action Groups
TOUCHIFY_ID_MENU_ROOT="Touchify"
#-----------------#
# Action IDs
TOUCHIFY_ID_ACTION_STYLES_BORDERLESSTOOLBARS="touchify_toolbarBorder"
TOUCHIFY_ID_ACTION_STYLES_PRIVACYMODE="Privacy Mode"
TOUCHIFY_ID_ACTION_STYLES_TABHEIGHT="touchify_tabHeight"
TOUCHIFY_ID_ACTION_STYLES_DOCKEDBRUSHEDITOR="touchify_styles_docked_brush_editor"
TOUCHIFY_ID_ACTION_STYLES_DOCKEDBRUSHEDITORZOOMFIX="touchify_styles_brush_editor_zoom_fix"
TOUCHIFY_ID_ACTION_STYLES_MENU="touchify_styles_menu"

TOUCHIFY_ID_ACTION_CANVAS_SHOWTOOLBOX="touchify_showToolbox"
TOUCHIFY_ID_ACTION_CANVAS_SHOWTOOLSHELF_ALPHA="touchify_showToolshelf"
TOUCHIFY_ID_ACTION_CANVAS_SHOWTOOLSHELF_BETA="touchify_showToolshelfAlt"
TOUCHIFY_ID_ACTION_CANVAS_SHOWTOOLSHELF_GAMMA="touchify_canvas_showtoolshelf_gamma"
TOUCHIFY_ID_ACTION_CANVAS_SHOWTOOLSHELF_DELTA="touchify_canvas_showtoolshelf_delta"
TOUCHIFY_ID_SETTINGS_WIDGETPAD_LAYOUTS_MENU = "touchify_canvas_layouts_menu"
TOUCHIFY_ID_SETTINGS_WIDGETPAD_OPTIONS_MENU = "touchify_canvas_options_menu"

TOUCHIFY_ID_ACTION_DOCKERUTILS_MENU="touchify_dockerutils_menu"
TOUCHIFY_ID_ACTION_DOCKERUTILS_TOGGLEDOWN="touchify_dockerutils_toggledown"
TOUCHIFY_ID_ACTION_DOCKERUTILS_TOGGLEUP="touchify_dockerutils_toggleup"
TOUCHIFY_ID_ACTION_DOCKERUTILS_TOGGLELEFT="touchify_dockerutils_toggleleft"
TOUCHIFY_ID_ACTION_DOCKERUTILS_TOGGLERIGHT="touchify_dockerutils_toggleright"

TOUCHIFY_ID_ACTION_OTHER_SHOWPOPUPPALETTE="touchify_showPopupPalette"
TOUCHIFY_ID_ACTION_OTHER_SHOWMENUBARPOPUP="touchify_showPopupMenu"
TOUCHIFY_ID_ACTION_CONFIGURE="touchify_configure"
#-----------------#
# Docker IDs
TOUCHIFY_ID_DOCKER_TOOLSHELFDOCKER="Touchify/ToolshelfDocker"
TOUCHIFY_ID_DOCKER_TOOLBOX="Touchify/TouchifyToolbox"
#-----------------#
# Setting Sections
TOUCHIFY_ID_SETTINGS_TOOLSHELF="Touchify/Toolshelfs"
TOUCHIFY_ID_SETTINGS_WIDGETPAD="Touchify/WidgetPads"
TOUCHIFY_ID_SETTINGS_POPUPS_FIXED_LOCATIONS="Touchify/Popups/Fixed/Locations"
TOUCHIFY_ID_SETTINGS_POPUPS_LAST_LOCATIONS="Touchify/Popups/Normal/Locations"

TOUCHIFY_TIMER_MAIN_INTERVAL=250
TOUCHIFY_ID_ACTION_REGISTERED="touchify_registry_"


#Internals
TOUCHIFY_WIDGETPROPS_EDITING_ALLOWED="TouchifyEditMode_Allow"
TOUCHIFY_WIDGETPROPS_EDITING_SELECTED="TouchifyEditMode_Selected"


