# Action Groups
TOUCHIFY_ID_ACTIONS_ROOT="Touchify"

# Action Subgroups
TOUCHIFY_ID_ACTIONS_HOTKEY="hotkey"
TOUCHIFY_ID_ACTIONS_WORKSPACE="workspace"
TOUCHIFY_ID_ACTIONS_DOCKER="docker"
TOUCHIFY_ID_ACTIONS_POPUP="popup"
TOUCHIFY_ID_ACTIONS_DOCKER_GROUP="docker_group"

# Action IDs
TOUCHIFY_AID_ACTIONS_WORKSPACE="workspace"
TOUCHIFY_AID_ACTIONS_DOCKER="docker"
TOUCHIFY_AID_ACTIONS_POPUP="popup"
TOUCHIFY_AID_ACTIONS_DOCKER_GROUP="group"

TOUCHIFY_AID_SHOW_TOOLBOX="touchify_showToolbox"
TOUCHIFY_AID_SHOW_TOOL_OPTIONS="touchify_showToolOptions"

# Other IDs
TOUCHIFY_TOOLBOX_DOCKER_ID='TouchifyToolbox'

# Krita IDs
KRITA_TOOL_OPTIONS_DOCKER_ID='sharedtooldocker'